language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y $(cut -d, -f2 requirements-system.csv | tail -n +2)
install: make devel
script: nosetests -A "not service == 'systemd'"